
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:8 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:8 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.9.8+b34f75857 для .NET Framework
      Сборка начата 10.07.2025 20:48:49.
      
      Проект "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\3.29.2\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Структурированный вывод включен. Форматирование диагностики компилятора будет отражать иерархию ошибок. Подробнее см. https://aka.ms/cpp/structured-output.
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      VcpkgTripletSelection:
        Using triplet "x86-windows" from "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\"
        Using normalized configuration "Release"
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x86\\CL.exe /c /I"C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\include" /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\lib" /LIBPATH:"C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\3.29.2\\CompilerIdC\\CompilerIdC.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\Sg\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\3.29.2\\CompilerIdC\\CompilerIdC.exe" "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"
        "pwsh.exe" не является внутренней или внешней
        командой, исполняемой программой или пакетным файлом.
        Выход из команды "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\Sg\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\3.29.2\\CompilerIdC\\CompilerIdC.exe" "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"" с кодом 9009.
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\Sg\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\3.29.2\\CompilerIdC\\CompilerIdC.exe" "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x86\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\3.29.2\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:02.52
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        F:/SearchEngine_asio_new/utf8proc-2.10.0/utf8proc-2.10.0/build_x86/CMakeFiles/3.29.2/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:8 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "F:/SearchEngine_asio_new/utf8proc-2.10.0/utf8proc-2.10.0/build_x86/CMakeFiles/CMakeScratch/TryCompile-usgt2y"
      binary: "F:/SearchEngine_asio_new/utf8proc-2.10.0/utf8proc-2.10.0/build_x86/CMakeFiles/CMakeScratch/TryCompile-usgt2y"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'F:/SearchEngine_asio_new/utf8proc-2.10.0/utf8proc-2.10.0/build_x86/CMakeFiles/CMakeScratch/TryCompile-usgt2y'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_8aab0.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.9.8+b34f75857 для .NET Framework
        Сборка начата 10.07.2025 20:48:51.
        
        Проект "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\cmTC_8aab0.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_8aab0.dir\\Debug\\".
          Структурированный вывод включен. Форматирование диагностики компилятора будет отражать иерархию ошибок. Подробнее см. https://aka.ms/cpp/structured-output.
          Создание каталога "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\Debug\\".
          Создание каталога "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\unsuccessfulbuild".
        VcpkgTripletSelection:
          Using triplet "x86-windows" from "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\"
          Using normalized configuration "Release"
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x86\\CL.exe /c /I"C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\include" /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8aab0.dir\\Debug\\\\" /Fd"cmTC_8aab0.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.39.33523 для x86
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /I"C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\include" /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8aab0.dir\\Debug\\\\" /Fd"cmTC_8aab0.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\Debug\\cmTC_8aab0.exe" /INCREMENTAL /ILK:"cmTC_8aab0.dir\\Debug\\cmTC_8aab0.ilk" /NOLOGO /LIBPATH:"C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\lib" /LIBPATH:"C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"F:/SearchEngine_asio_new/utf8proc-2.10.0/utf8proc-2.10.0/build_x86/CMakeFiles/CMakeScratch/TryCompile-usgt2y/Debug/cmTC_8aab0.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/SearchEngine_asio_new/utf8proc-2.10.0/utf8proc-2.10.0/build_x86/CMakeFiles/CMakeScratch/TryCompile-usgt2y/Debug/cmTC_8aab0.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_8aab0.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_8aab0.vcxproj -> F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\Debug\\cmTC_8aab0.exe
        AppLocalFromInstalled:
          pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\Sg\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\Debug\\cmTC_8aab0.exe" "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\bin" "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\cmTC_8aab0.write.1u.tlog" "cmTC_8aab0.dir\\Debug\\vcpkg.applocal.log"
          "pwsh.exe" не является внутренней или внешней
          командой, исполняемой программой или пакетным файлом.
          Выход из команды "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\Sg\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\Debug\\cmTC_8aab0.exe" "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\bin" "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\cmTC_8aab0.write.1u.tlog" "cmTC_8aab0.dir\\Debug\\vcpkg.applocal.log"" с кодом 9009.
          "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\\Users\\Sg\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\Debug\\cmTC_8aab0.exe" "C:\\Users\\Sg\\vcpkg\\installed\\x86-windows\\bin" "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\cmTC_8aab0.write.1u.tlog" "cmTC_8aab0.dir\\Debug\\vcpkg.applocal.log"
        FinalizeBuildStatus:
          Файл "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_8aab0.dir\\Debug\\cmTC_8aab0.tlog\\cmTC_8aab0.lastbuildstate".
        Сборка проекта "F:\\SearchEngine_asio_new\\utf8proc-2.10.0\\utf8proc-2.10.0\\build_x86\\CMakeFiles\\CMakeScratch\\TryCompile-usgt2y\\cmTC_8aab0.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:01.75
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:170 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:8 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/HostX64/x86/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:207 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:8 (project)"
    message: |
      Running the C compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/HostX64/x86/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.39.33523.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
